server {
    listen 80;
    server_name www.gramavani.lc gramavani.lc;

    root /var/www/gramavani/public;
    index index.php index.html;

    access_log /var/log/nginx/gramavani.access.log;
    error_log  /var/log/nginx/gramavani.error.log;

    include /etc/nginx/snippets/static-files.conf;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        set $php_upstream php_news:9000;
        fastcgi_pass $php_upstream;
    }
}

