server {
    listen 80;
    server_name www.winesapp.lc m.winesapp.lc winesapp.lc;

    root /var/www/winesapp_main/app/webroot;
    index index.php index.html;

    access_log /var/log/nginx/winesapp.access.log;
    error_log  /var/log/nginx/winesapp.error.log;

    include /etc/nginx/snippets/static-files.conf;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        set $php_upstream php_liq:9000;
        fastcgi_pass $php_upstream;
    }
}

