server {
    listen 80;
    server_name closingstock.winesapp_v1.lc;

    root /var/www/winesapp_v1_mobile/app/webroot;
    index index.php index.html;

    access_log /var/log/nginx/winesapp_v1_mobile.access.log;
    error_log  /var/log/nginx/winesapp_v1_mobile.error.log;

    include /etc/nginx/snippets/static-files.conf;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass php_liq_v1_mobile:9000;
    }
}

