server {
    listen 80;
    server_name www.winesapp_v1.lc m.winesapp_v1.lc winesapp_v1.lc;

    root /var/www/winesapp_v1/app/webroot;
    index index.php index.html;

    access_log /var/log/nginx/winesapp_v1.access.log;
    error_log  /var/log/nginx/winesapp_v1.error.log;

    include /etc/nginx/snippets/static-files.conf;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        set $php_upstream php_liq_v1:9000;
        fastcgi_pass $php_upstream;
    }
}

